<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ConvertToUHD.Core\ConvertToUHD.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WindowsAPICodePack.Shell.CommonFileDialogs.Wpf" Version="1.1.5.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="office">
		<HintPath>C:\Windows\assembly\GAC_MSIL\office\15.0.0.0__71e9bce111e9429c\office.dll</HintPath>
	    <Private>true</Private>
	</Reference>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
	  <PlatformTarget>x64</PlatformTarget>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
